// Projectile type definitions
export const projectileTypes = {
  basic: {
    type: 'basic',
    color: 0xff0000,
    speed: 0.15,
    damage: 5,
    life: 3000,
  },
  laser: {
    type: 'laser',
    color: 0xff3300,
    speed: 0.2,
    damage: 5,
    life: 3000,
    trail: true,
  },
  heavylaser: {
    type: 'heavylaser',
    color: 0xff0000,
    speed: 0.28,
    damage: 25,
    life: 4000,
    trail: true,
    penetrating: true,
    radius: 0.15,
  },
  bomb: {
    type: 'bomb',
    color: 0xffaa00,
    speed: 0.1,
    damage: 20,
    life: 5500,
    radius: 0.18,
    explosive: true,
    explosionRadius: 2.0,
    gravity: 0.001,
    pulsate: true,
    unstable: true,
  },
  plasma: {
    type: 'plasma',
    color: 0x00aaff,
    speed: 0.18,
    damage: 15,
    life: 4500,
    trail: true,
    pulsate: true,
    heatSeek: true,
    radius: 0.12,
    penetrating: true,
  },
  missile: {
    type: 'missile',
    color: 0xff8800,
    speed: 0.1,
    damage: 30,
    life: 7000,
    trail: true,
    guided: true,
    explosive: true,
    explosionRadius: 2.0,
    acceleration: 0.002,
  },
  nova: {
    type: 'nova',
    color: 0xff00ff,
    speed: 0.05,
    damage: 35,
    life: 5000,
    radius: 0.25,
    pulsate: true,
    explosive: true,
    explosionRadius: 3.0,
    splitCount: 6,
  },
};
